### ISSUE TITLE
* Player ID not found. Please ensure you typed it correctly. 147-197-267

### ISSUE THREAD

**Issue by Amit30swgoh** [jedi-gg/swgoh.gg.public#421]
Hello there!

https://swgoh.gg/p/147197267/ 
Amit 30
just moved to new guild 
tried to update sync did not change id or something only clicked on "update profile"
i t say above * Player ID not found. Please ensure you typed it correctly would you want me to post my id?

**Comment by Amit30swgoh** [comment]
will have a look ty so much love u

‫בתאריך יום ו׳, 5 באוק׳ 2018 ב-18:54 מאת ‪sanktanglia‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Amit30swgoh** [comment]
why i dont see average rank on my guild channel ty

‫בתאריך שבת, 6 באוק׳ 2018 ב-1:36 מאת ‪Amit Shriqui‬‏ <‪amitshriqui@gmail.com
‬‏>:‬

**Comment by Raifikus** [comment]
I’m having this same issue....help?

**Comment by sanktanglia** [comment]
@Raifikus what is your ally code? you are probably putting in the wrong player id

**Comment by Raifikus** [comment]
674515359

**Comment by Raifikus** [comment]
Got it, I wasn’t using the - in front. I tried it just for kicks haha and it worked. Thank you

**Comment by Aveane** [comment]
Same here. Everything was fine and out of nowhere after hitting "Update" button I have that info. I'm sure my Player ID is correct.
https://swgoh.gg/p/945133232/

**Comment by Cimmeron** [comment]
Hi,
 Been using swgoh.gg for a while now then all of a sudden yesterday when I went update I get player id not found. If I use the look up for the player id and use that one, it is the same as what I have enter and I still get player id not found. I also tried clearing the cache on the browser with no luck. After I go in I'll get the updated a few seconds ago but it is actually not sync the account. This is happening for my account and my girlfriend's account listed below. 

https://swgoh.gg/p/662455698/
https://swgoh.gg/p/745525398/

**Comment by sanktanglia** [comment]
well get it fixed up, thanks

**Comment by CollinGraf314** [comment]
I'm positive my player ID is correct, I've used your tool, I've tried putting a '-' before it, nothing is working. Could you please help me? 
Player ID: DXdHWQ72Sv2J6rgAiSGyWQ
Ally Code: 798-364-712

**Comment by jedifather73** [comment]
I’m having the same problem all of a sudden. https://swgoh.gg/p/541919578/

**Comment by sanktanglia** [comment]
@jedifather73 we have to update our tools for the new patch, should be working soon

**Comment by sanktanglia** [comment]
should be working now

**Comment by jedifather73** [comment]
It is. Thank you!

**Comment by W4RB4CON** [comment]
Having same issue. I am new but entering a Player ID seems pretty cut n dry. Tried every which way but no luck even entered ally code for SnG still no luck.

**Comment by sanktanglia** [comment]
whats your ally code and player id?

**Comment by Vacant-Pirate** [comment]
Same no player I’d found 
Please help
https://swgoh.gg/p/423726933/

**Comment by Cimmeron** [comment]
Hi,
 Seem this problem is happening again on both profiles. Seemed to happen after Windows wanted to update and it closed the browser for me. Not sure if it is related or not just what happened.


https://swgoh.gg/p/662455698/
https://swgoh.gg/p/745525398/

**Comment by sanktanglia** [comment]
@Vacant-Pirate you can pm me on reddit @Cimmeron ill look into it, the auto sync is working def and the manual sync runs on a slightly different process so ill see whats up

**Comment by sanktanglia** [comment]
@Cimmeron should be fixed up now

**Comment by Cimmeron** [comment]
Thanks.

**Comment by Kenscotsman** [comment]
Same not found
Please help
https://swgoh.gg/p/975621232/

**Comment by Aros1997** [comment]
hello i am having the same problem as well as i typed it over 5 times and it still wont go through

**Comment by scobenes** [comment]
This is most likely an old bug, if you ever need help figuring out player id go to this tool https://swgoh.gg/id-help/
